# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import inspect_pb2 as inspect__pb2


class SystemInspectStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.port_is_open = channel.unary_unary(
        '/inspect.SystemInspect/port_is_open',
        request_serializer=inspect__pb2.PortCheckRequest.SerializeToString,
        response_deserializer=inspect__pb2.PortCheckReply.FromString,
        )


class SystemInspectServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def port_is_open(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SystemInspectServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'port_is_open': grpc.unary_unary_rpc_method_handler(
          servicer.port_is_open,
          request_deserializer=inspect__pb2.PortCheckRequest.FromString,
          response_serializer=inspect__pb2.PortCheckReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'inspect.SystemInspect', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
